apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: go76i9hhx-go
  janus-idp.io/tekton: go76i9hhx-go
  backstage.io/kubernetes-id: go76i9hhx-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: go76i9hhx-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
