apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: go76i9hhx-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go76i9hhx-go 
  name: go76i9hhx-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: go76i9hhx-go 
